export const USER_LOGIN_IN_REQUEST = "USER_LOGIN_IN_REQUEST";
export const USER_LOGIN_IN_SUCCESS = "USER_LOGIN_IN_SUCCESS";
export const USER_LOGIN_IN_ERROR = "USER_LOGIN_IN_ERROR";
export const UPDATE_ADDRESS = "UPDATE_ADDRESS";
export const LOGGED_OUT_USER_CART = "LOGGED_OUT_USER_CART";
export const USER_LOGOUT = "USER_LOGOUT";

export const PRODUCTS_FETCH_REQUEST = "PRODUCTS_FETCH_REQUEST";
export const PRODUCTS_FETCH_SUCCESS = "PRODUCTS_FETCH_SUCCESS";
export const PRODUCTS_FETCH_ERROR = "PRODUCTS_FETCH_ERROR";


export const PRODUCTS_DETAILS_FETCH_REQUEST = "PRODUCTS_DETAILS_FETCH_REQUEST";
export const PRODUCTS_DETAILS_FETCH_SUCCESS = "PRODUCTS_DETAILS_FETCH_SUCCESS";
export const PRODUCTS_DETAILS_FETCH_ERROR = "PRODUCTS_DETAILS_FETCH_ERROR";

export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_ERROR = "ADD_TO_CART_ERROR";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const EMPTY_CART = "EMPTY_CART";


export const ORDERS_FETCH_REQUEST = "ORDERS_FETCH_REQUEST";
export const ORDERS_FETCH_SUCCESS = "ORDERS_FETCH_SUCCESS";
export const ORDERS_FETCH_ERROR = "ORDERS_FETCH_ERROR";
export const ORDER_DETAILS_FETCH_SUCCESS = "ORDER_DETAILS_FETCH_SUCCESS";
